# Generated by Django 5.0.1 on 2024-01-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
